.claspignore, .gitignore, appsscript.json, src/sheet/main.js
close #15 
- https://github.com/tam-bourine/miyamoto-ex
- https://qiita.com/HeRo/items/4e65dcc82783b2766c03#claspjson-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AErootdir
=> GAS用のclasp設定を追加

docs/gas_api/OpenApi.json
close #41 
[コーディング規約](https://github.com/airbnb/javascript) に合わせてキー名をキャメルケースに変更する
=> OpenApiのキー名をキャメルケースに変更

src/functions/.env.example, src/functions/config.json
環境変数の見本をfirebase内の環境変数の構成（object）と合わせました。（#53）
=> .env.exampleの構成を変更

docs/gas_api/OpenApi.json
=> Open APIの修正

package.json, src/functions/blocks/messages/modal.ts, src/functions/commands/newClub.ts, src/gas/controllers/InvalidActionController.ts, src/gas/models/Club/ApproveModel.ts, src/gas/models/Club/RegistModel.ts, src/gas/models/Clubs/GetModel.ts, src/gas/routes.ts, src/gas/shared/Response.ts
=> Lint バグ やっと直ったぞ〜

src/gas/models/Club/ApproveModel.ts, src/gas/shared/Constants.ts
https://github.com/tam-bourine/club-manager/issues/107
なおせ〜〜〜 POST approve ちゃんと動いてくれ
- POST action=approve が正常に動くかどうか
- approve で公認のセルが更新される
- approve の際に部活動シートを作成する機能については [別 issue](https://github.com/tam-bourine/club-manager/issues/123) にて対応
=> POST approve で1行目が消し飛ぶバグの修正

package-lock.json, package.json
- ts-node-devを入れる
- ホットリロードが効く
- 開発環境で実行時毎回トランスパイルしなくて済む
=> ts-node-devを入れたい

package-lock.json, src/gas/models/Club/RegistModel.ts, src/gas/shared/types/RegistInterface.ts, src/gas/shared/types/ResponseInterface.ts
=> GAS 創部申請のリクエストボディーの形式変更

src/functions/kibela/queries/user.ts
=> kibelaAPIにてemailからuserを検索する関数

docs/columns/clubs.json
=> "活動内容"カラムをjsonに追加し忘れていたので追加

src/functions/blocks/inputClub.ts, src/functions/blocks/messages/modal.ts, src/functions/commands/newClub.ts, src/functions/config/clubConfig.ts, src/functions/types/Messages.ts
* 創部申請のモーダルにフィールドを追加・削除
手元で動作確認済みです
=> 創部申請モーダルの項目変更

docs/gas_api/OpenApi.json, src/gas/controllers/Club/ApproveController.ts, src/gas/models/Club/ApproveModel.ts, src/gas/shared/Constants.ts, src/gas/shared/types/ApproveInterface.ts, src/gas/shared/types/UtilityTypes.ts
- POST approve
- `isApproved` が `true` の場合に`<部活動名>` のシートを作成
- 作成されたシートにメンバーを追加
- 正常に動くかどうか
- `ApproveModel.ts` がかなりファットになることが予想されるので、分離の必要性の吟味
=> GAS POST approve 時にシート作成・メンバー追加

src/functions/kibela/mutations/note.ts, src/functions/kibela/mutations/user.ts, src/functions/kibela/queries/group.ts, src/functions/kibela/queries/note.ts, src/functions/kibela/queries/user.ts
=> kibelaユーザーを部活グループに入れる

src/gas/models/Club/RegistModel.ts
=> GAS 創部申請時に部活チャンネルIDを追記するように修正

package.json, tsconfig.json
=> fix: 🐛 remain functions

.gcloudignore
=> fix: 🐛 gcloudignore

src/constant.ts, src/index.ts
=> fix: 🐛 remain process.env.PORT

docs/gas_api/OpenApi.json, src/gas/models/Club/ApproveModel.ts, src/gas/shared/Constants.ts, src/gas/shared/types/ResponseInterface.ts
- approve が `success: true` の際に返すデータを以下のように変更
```json
{
"status": 200,
"message": "200 OK",
"success": true,
"club": {
"name": "Piyo",
"kibelaUrl": "https://piyo.kibe.la/notes/12345",
"userIds": [
"XX112233"
]
}
}
```
=> GAS創部承認 レスポンス修正

package.json
=> chore: 🤖 add `npm ci` to run serve on GCR

package.json
=> fix: 🐛 npm script

package.json
=> fix: 🐛 add tsc script

package.json
=> fix: 🐛 tsc script

src/commands/newClub.ts, src/index.ts, src/shortcuts/newClub.ts
=> 創部申請(ショートカットver.)

Makefile, docker/Dockerfile, docker/docker-compose.yml, src/api/slack/user.ts, src/constant.ts, src/index.ts, src/types/slack/User.ts
=> feat: 🎸 docker

package.json, src/commands/newClub.ts, src/config/modalConfig.ts, src/gas/models/Club/JoinModel.ts, src/index.ts, src/modal/modalTemplate.ts, src/shortcuts/newClub.ts
=> 入部処理後のResponseにKibelaUrl等を含める

cloudbuld.yaml
=> feat: 🎸 add yaml

cloudbuild.yaml
=> fix: 🐛 typo

cloudbuild.yaml
=> fix: 🐛 quotation

src/index.ts
=> fix: fix/tt-bundle-isDisplayCapacity

Makefile, cloudbuild.yaml, docker/Dockerfile, package.json
=> fix: 🐛 a lot of aroud gcr

.gcloudignore, cloudbuild.yaml, src/constant.ts
=> feat: 🎸 gcr auto deployment

Makefile, cloudbuild.yaml
=> fix: 🐛 cloud build

Makefile, cloudbuild.yaml
=> fix: 🐛 cloud build (#226)

.github/workflows/lint.yml
=> chore: 🤖 make develop branch lint target

src/commands/newClub.ts, src/config/modalConfig.ts, src/index.ts, src/shortcuts/joinClub.ts, src/shortcuts/newClub.ts
=> SlashCommand -> Shorcut

.github/workflows/lint.yml
- develop -> main するときに push と pull_request の両方で走っていたので修正
- 基本的に pull_request に対するイベントをトリガーに走らせる
- push 時は様子を見て追加
=> Actions で lint するタイミングの修正

docs/gas_api/OpenApi.json, src/gas/models/Club/ApproveModel.ts, src/gas/models/Club/JoinModel.ts, src/gas/models/Clubs/GetModel.ts, src/gas/shared/types/ApproveInterface.ts, src/gas/shared/types/JoinInterface.ts
=> GASをUUID管理に差し戻す

src/commands/newClub.ts, src/shortcuts/joinClub.ts, src/shortcuts/newClub.ts
=> join clubのモーダル表示時だけackをawaitするようにした

src/commands/newClub.ts, src/index.ts, src/shortcuts/joinClub.ts
=> ack()をawait

cloudbuild.yaml
=> fix: 🐛 yaml

Makefile, cloudbuild.yaml
=> chore: 🤖 fix

.github/workflows/deploy.yml, .github/workflows/lint.yml, scripts/setup_clasp_json.sh, scripts/setup_clasprc_json.sh
=> Push & deploy to GAS on Actions

Procfile
=> chore: 🤖 add procfile

Procfile
=> fix: 🐛 procfile command

src/index.ts
=> fix: 🐛 processBeforeResponse
